---
name: pdd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pdd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: volodya-lombrozo/pdd-action@master
