---
name: pdd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pdd:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: volodya-lombrozo/pdd-action@master
