---
name: xcop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: g4s8/xcop-action@v1.3
